name: Deploy S3 Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640960678132:role/github-s3-deploy-role
          aws-region: us-east-1

      - name: Verify Assumed Role
        run: aws sts get-caller-identity

      - name: Create S3 Bucket (if not exists)
        run: |
          aws s3 mb s3://static-web-hosting-vijay49 || true

      - name: Upload Website Files
        run: |
          ls -lart
          # aws s3 sync README.md s3://static-web-hosting-vijay49 --delete